server:
  port: 5802
  servlet:
    context-path: /review-that-matters/

spring:
  datasource:
    url: jdbc:mysql://containers-us-west-37.railway.app:5802/railway
    username: root
    password: dLB17lokOPUHXLzu8Q5h
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

